#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Script generated by Vivado on Wed Jan 15 18:00:45 CET 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : uartlite.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : uartlite.sh
#                uartlite.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                uartlite.sh [-reset_run]
#                uartlite.sh [-reset_log]
#                uartlite.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'uartlite.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip xpm generic_baseblocks_v2_1_2 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_31 fifo_generator_v13_2_10 axi_data_fifo_v2_1_30 axi_crossbar_v2_1_32 xil_defaultlib axi_protocol_converter_v2_1_31 axi_clock_converter_v2_1_30 blk_mem_gen_v8_4_8 axi_dwidth_converter_v2_1_31 util_vector_logic_v2_0_4 microblaze_v11_0_13 lib_cdc_v1_0_3 proc_sys_reset_v5_0_15 lmb_v10_v3_0_14 lmb_bram_if_cntlr_v4_0_24 iomodule_v3_1_10 axi_vip_v1_1_17 zynq_ultra_ps_e_vip_v1_0_17 axi_lite_ipif_v3_0_4 lib_pkg_v1_0_4 lib_srl_fifo_v1_0_4 axi_uartlite_v2_0_35)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "uartlite.sh - Script generated by export_simulation (Vivado v2024.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./uartlite.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "/opt/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/opt/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "/opt/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vlogan -work generic_baseblocks_v2_1_2 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_register_slice_v2_1_31 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_10 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/1443/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work fifo_generator_v13_2_10 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/1443/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_10 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/1443/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_data_fifo_v2_1_30 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/9692/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_crossbar_v2_1_32 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/e9d8/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_xbar_0/sim/uartlite_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_protocol_converter_v2_1_31 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3c06/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_clock_converter_v2_1_30 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/80bf/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work blk_mem_gen_v8_4_8 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/09bd/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_dwidth_converter_v2_1_31 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/14b9/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_auto_us_df_0/sim/uartlite_auto_us_df_0.v" \
  "../../../bd/uartlite/ip/uartlite_auto_us_0/sim/uartlite_auto_us_0.v" \
  "../../../bd/uartlite/ip/uartlite_auto_cc_2/sim/uartlite_auto_cc_2.v" \
  "../../../bd/uartlite/ip/uartlite_auto_cc_0/sim/uartlite_auto_cc_0.v" \
  "../../../bd/uartlite/ip/uartlite_auto_cc_1/sim/uartlite_auto_cc_1.v" \
  "../../../bd/uartlite/ip/uartlite_auto_ds_0/sim/uartlite_auto_ds_0.v" \
  "../../../bd/uartlite/ip/uartlite_auto_pc_0/sim/uartlite_auto_pc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ipshared/b930/sources_1/imports/binary_latch_counter/binary_latch_counter.sv" \
  "../../../bd/uartlite/ip/uartlite_binary_latch_counter_0_0/sim/uartlite_binary_latch_counter_0_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_c_clk_mmcm_200_0/uartlite_c_clk_mmcm_200_0_clk_wiz.v" \
  "../../../bd/uartlite/ip/uartlite_c_clk_mmcm_200_0/uartlite_c_clk_mmcm_200_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work util_vector_logic_v2_0_4 $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/fd7b/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_c_clk_mmcm_200_locked_0/sim/uartlite_c_clk_mmcm_200_locked_0.v" \
  "../../../bd/uartlite/ip/uartlite_clk_mmcm_reset_0/sim/uartlite_clk_mmcm_reset_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work microblaze_v11_0_13 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/aa1c/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_0/sim/bd_698a_microblaze_I_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_cdc_v1_0_3 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_15 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_1/sim/bd_698a_rst_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lmb_v10_v3_0_14 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/7495/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_2/sim/bd_698a_ilmb_0.vhd" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_3/sim/bd_698a_dlmb_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lmb_bram_if_cntlr_v4_0_24 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3eb2/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_4/sim/bd_698a_dlmb_cntlr_0.vhd" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_5/sim/bd_698a_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_6/sim/bd_698a_lmb_bram_I_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_7/sim/bd_698a_second_dlmb_cntlr_0.vhd" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_8/sim/bd_698a_second_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_9/sim/bd_698a_second_lmb_bram_I_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work iomodule_v3_1_10 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/213d/hdl/iomodule_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/ip/ip_10/sim/bd_698a_iomodule_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/bd_0/sim/bd_698a.v" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_0/sim/uartlite_ddr4_0_0_microblaze_mcs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy_behav.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob_byte.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/clocking/ddr4_phy_v2_2_pll.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_tristate_wrapper.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_riuor_wrapper.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_control_wrapper.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_byte_wrapper.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_bitslice_wrapper.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/phy/uartlite_ddr4_0_0_phy_ddr4.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/ip_top/uartlite_ddr4_0_0_phy.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_wtr.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ref.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_rd_wr.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_periodic.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_group.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_merge_enc.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_gen.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_fi_xor.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_dec_fix.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_buf.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ctl.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_c.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_ap.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_p.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_mux_p.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_c.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_a.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_timer.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_rank.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/controller/ddr4_v2_2_mc.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_wr_data.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_rd_data.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_cmd.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ui/ddr4_v2_2_ui.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_ar_channel.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_aw_channel.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_b_channel.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_arbiter.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_fsm.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_translator.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_fifo.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_incr_cmd.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_r_channel.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_w_channel.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wr_cmd_fsm.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wrap_cmd.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_a_upsizer.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_register_slice.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_upsizer.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_axic_register_slice.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_and.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_and.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_or.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_or.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_command_fifo.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel_static.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_r_upsizer.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi/ddr4_v2_2_w_upsizer.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_addr_decode.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_read.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg_bank.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_top.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_write.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/clocking/ddr4_v2_2_infrastructure.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_bram.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_write.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_byte.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_bit.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_sync.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_read.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_rd_en.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_pi.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_mc_odt.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_debug_microblaze.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx_data.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_config_rom.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_addr_decode.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_top.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_arbiter.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_cal.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_chipscope_xsdb_slave.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/ddr4_v2_2_dp_AB9.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top/uartlite_ddr4_0_0.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top/uartlite_ddr4_0_0_ddr4.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top/uartlite_ddr4_0_0_ddr4_mem_intfc.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal/uartlite_ddr4_0_0_ddr4_cal_riu.sv" \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_0/tb/uartlite_ddr4_0_0_microblaze_mcs_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/uartlite/ip/uartlite_ddr4_0_sys_reset_0/sim/uartlite_ddr4_0_sys_reset_0.vhd" \
  "../../../bd/uartlite/ip/uartlite_proc_sys_reset_0_0/sim/uartlite_proc_sys_reset_0_0.vhd" \
  "../../../bd/uartlite/ip/uartlite_proc_sys_reset_1_0/sim/uartlite_proc_sys_reset_1_0.vhd" \
  "../../../bd/uartlite/ip/uartlite_util_ds_buf_0_0/util_ds_buf.vhd" \
  "../../../bd/uartlite/ip/uartlite_util_ds_buf_0_0/sim/uartlite_util_ds_buf_0_0.vhd" \
  "../../../bd/uartlite/ip/uartlite_util_ds_buf_1_0/sim/uartlite_util_ds_buf_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work axi_vip_v1_1_17 $vlogan_opts -sverilog +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/4d04/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work zynq_ultra_ps_e_vip_v1_0_17 $vlogan_opts -sverilog +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/ip/uartlite_zynq_ultra_ps_e_0_0/sim/uartlite_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_pkg_v1_0_4 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_srl_fifo_v1_0_4 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_uartlite_v2_0_35 $vhdlan_opts \
  "../../../../project_1.gen/sources_1/bd/uartlite/ipshared/2959/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/uartlite/ip/uartlite_axi_uartlite_0_0/sim/uartlite_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/ec67/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/3242" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ipshared/a317/hdl" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/ip_top" +incdir+"../../../../project_1.gen/sources_1/bd/uartlite/ip/uartlite_ddr4_0_0/rtl/cal" +incdir+"/opt/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/uartlite/sim/uartlite.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.uartlite xil_defaultlib.glbl -o uartlite_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./uartlite_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key uartlite_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc uartlite_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./uartlite.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: uartlite.sh [-help]\n\
Usage: uartlite.sh [-step]\n\
Usage: uartlite.sh [-lib_map_path]\n\
Usage: uartlite.sh [-reset_run]\n\
Usage: uartlite.sh [-reset_log]\n\
Usage: uartlite.sh [-keep_index]\n\
Usage: uartlite.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
