# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/vivado/constraints/base.xdc

# Block Designs: bd/uartlite/uartlite.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite || ORIG_REF_NAME==uartlite} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_zynq_ultra_ps_e_0_0/uartlite_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==uartlite_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_axi_uartlite_0_0/uartlite_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_axi_uartlite_0_0 || ORIG_REF_NAME==uartlite_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_xbar_1/uartlite_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_xbar_1 || ORIG_REF_NAME==uartlite_xbar_1} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_auto_ds_0/uartlite_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_auto_ds_0 || ORIG_REF_NAME==uartlite_auto_ds_0} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_auto_pc_0/uartlite_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_auto_pc_0 || ORIG_REF_NAME==uartlite_auto_pc_0} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_auto_cc_1/uartlite_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_auto_cc_1 || ORIG_REF_NAME==uartlite_auto_cc_1} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_auto_ds_1/uartlite_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_auto_ds_1 || ORIG_REF_NAME==uartlite_auto_ds_1} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_auto_pc_1/uartlite_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_auto_pc_1 || ORIG_REF_NAME==uartlite_auto_pc_1} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_auto_cc_0/uartlite_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_auto_cc_0 || ORIG_REF_NAME==uartlite_auto_cc_0} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_ps8_0_axi_periph_1/uartlite_ps8_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_ps8_0_axi_periph_1 || ORIG_REF_NAME==uartlite_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_rst_ps8_0_299M_1/uartlite_rst_ps8_0_299M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_rst_ps8_0_299M_1 || ORIG_REF_NAME==uartlite_rst_ps8_0_299M_1} -quiet] -quiet

# IP: bd/uartlite/ip/uartlite_rst_ps8_0_99M_1/uartlite_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uartlite_rst_ps8_0_99M_1 || ORIG_REF_NAME==uartlite_rst_ps8_0_99M_1} -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_zynq_ultra_ps_e_0_0/uartlite_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_zynq_ultra_ps_e_0_0/uartlite_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==uartlite_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_axi_uartlite_0_0/uartlite_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_axi_uartlite_0_0 || ORIG_REF_NAME==uartlite_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_axi_uartlite_0_0/uartlite_axi_uartlite_0_0_ooc.xdc

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_axi_uartlite_0_0/uartlite_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_axi_uartlite_0_0 || ORIG_REF_NAME==uartlite_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_ds_0/uartlite_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_auto_ds_0 || ORIG_REF_NAME==uartlite_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_ds_0/uartlite_auto_ds_0_ooc.xdc

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_pc_0/uartlite_auto_pc_0_ooc.xdc

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_cc_1/uartlite_auto_cc_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_auto_cc_1 || ORIG_REF_NAME==uartlite_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_cc_1/uartlite_auto_cc_1_ooc.xdc

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_ds_1/uartlite_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_auto_ds_1 || ORIG_REF_NAME==uartlite_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_ds_1/uartlite_auto_ds_1_ooc.xdc

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_pc_1/uartlite_auto_pc_1_ooc.xdc

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_cc_0/uartlite_auto_cc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_auto_cc_0 || ORIG_REF_NAME==uartlite_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_auto_cc_0/uartlite_auto_cc_0_ooc.xdc

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_rst_ps8_0_299M_1/uartlite_rst_ps8_0_299M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_rst_ps8_0_299M_1 || ORIG_REF_NAME==uartlite_rst_ps8_0_299M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_rst_ps8_0_299M_1/uartlite_rst_ps8_0_299M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_rst_ps8_0_299M_1 || ORIG_REF_NAME==uartlite_rst_ps8_0_299M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_rst_ps8_0_99M_1/uartlite_rst_ps8_0_99M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_rst_ps8_0_99M_1 || ORIG_REF_NAME==uartlite_rst_ps8_0_99M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/ip/uartlite_rst_ps8_0_99M_1/uartlite_rst_ps8_0_99M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==uartlite_rst_ps8_0_99M_1 || ORIG_REF_NAME==uartlite_rst_ps8_0_99M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jing/RFSoC2x2-PYNQ/board/RFSoC2x2/base/project/project_1/project_1.gen/sources_1/bd/uartlite/uartlite_ooc.xdc
